const QUESTIONS_LONG_A2 = {
"1": ["Who did Person 2 go to the place with?","What did they do there?","Why might watching a movie and eating together make a weekend memorable?"],
"2": ["What sport is Person 2 playing this weekend?","What time does it start?","Why might Person 1 want to bring a drink to watch the game?"],
"3": ["How was Person 2's trip?","What did Person 2 like the most?","Why might trying local food be a highlight of traveling somewhere new?"],
"4": ["What new hobby did Person 2 start?","How often does Person 2 practice?","Why might practicing every day help someone improve quickly at a hobby?"],
"5": ["Why was Person 2 late for class?","What did the teacher say?","Why might setting an alarm help prevent being late in the future?"],
"6": ["Has Person 2 tried the food before?","Would Person 2 eat it again?","Why might trying new food at a restaurant be a fun experience?"],
"7": ["Where is Person 2's family planning a trip?","How long will they stay?","Why might spending time with family during a trip be especially meaningful?"],
"8": ["Has Person 2 finished the homework?","When will they meet to study together?","Why might studying with someone else make difficult homework easier?"],
"9": ["What gift did Person 2 receive?","What did they do to celebrate?","Why might a birthday party with food and family be a memorable celebration?"],
"10": ["Why is Person 2 tired today?","What did Person 2 watch?","Why might staying up late to watch something exciting be worth being tired the next day?"],
"11": ["When did Person 2 visit the new place?","Would Person 2 recommend it?","Why might a recommendation from a friend make someone want to visit a place?"],
"12": ["Did Person 2's team win the game?","Who did Person 2 watch it with?","Why might watching a game with family make the experience more exciting?"],
"13": ["When did Person 2 start studying for the test?","Does Person 2 feel confident?","Why might studying together help reduce nervousness before a test?"],
"14": ["Is Person 2 interested in joining the new club?","When does the club meet?","Why might joining a club be a good way to make new friends?"],
"15": ["How did Person 2's presentation go?","What feedback did the teacher give?","Why might feedback from a teacher help a student improve next time?"],
"16": ["What did Person 2 cook for dinner?","Who taught Person 2 how to make it?","Why might learning a recipe from family make cooking feel more meaningful?"],
"17": ["Has Person 2 decided what to wear?","What time does the festival start?","Why might going to a festival with a group of friends be more fun?"],
"18": ["Did Person 2 enjoy the movie?","Would Person 2 watch the sequel?","Why might people want to invite more friends to watch a movie they enjoyed?"],
"19": ["What did Person 2 order at the new place?","Was it expensive?","Why might trying a new drink place become a habit if the price is reasonable?"],
"20": ["Did Person 2 finish the book?","Was it hard to understand?","Why might having a favorite character make a book more enjoyable to read?"],
"21": ["Did Person 2's team win the match?","Will Person 2 go to the next one?","Why might a lively atmosphere at a match make people want to return?"],
"22": ["How long did Person 2 stay at the place?","Did Person 2 enjoy the local food?","Why might visiting somewhere with family create lasting memories?"],
"23": ["Is Person 2's hobby project finished?","How long did it take?","Why might Person 2 feel proud of finishing a long project?"],
"24": ["Who did Person 2 celebrate their birthday with?","What did they eat?","Why might celebrating with family make a birthday feel more special?"],
"25": ["What resources is Person 2 using to learn?","How much does Person 2 practice each day?","Why might learning something new without a teacher require extra dedication?"],
"26": ["What happened at the place yesterday?","Was Person 2 surprised by it?","Why might a community event bring more people together than expected?"],
"27": ["Did Person 2 enjoy the lesson today?","Will Person 2 continue next week?","Why might an encouraging coach make someone want to keep practicing?"],
"28": ["What theme did Person 2 choose for the party?","Did family help with decorating?","Why might decorating together as a family make an event feel more special?"],
"29": ["What did Person 2 learn at the workshop?","Was it useful for studying?","Why might a workshop about study techniques be helpful before exams?"],
"30": ["What is the new place like inside?","Did Person 2 buy anything?","Why might a new popular place attract many students quickly?"],
"31": ["Did the cooking turn out well?","Will Person 2 cook it again?","Why might cooking with family become a tradition over time?"],
"32": ["What is the new show about?","How many episodes are there?","Why might a recommendation from a friend make someone want to start a new show?"],
"33": ["Has Person 2 finished packing?","What is Person 2 most looking forward to?","Why might trying local food be an exciting part of a trip?"],
"34": ["What did the club discuss?","Will Person 2 go to the next meeting?","Why might a friendly group make someone want to keep attending a club?"],
"35": ["Who did Person 2 watch the fireworks with?","What was Person 2's favorite part?","Why might watching fireworks with family make the event feel more special?"],
"36": ["How has Person 2's first week of classes been?","Is the instructor helpful?","Why might a patient instructor make learning a new skill less stressful?"],
"37": ["What did Person 2 buy while shopping?","Did Person 2 spend a lot of money?","Why might shopping during a sale help someone save money?"],
"38": ["What features does the new app have?","Is it easy to use?","Why might an easy-to-use app encourage someone to keep using it?"],
"39": ["Who did Person 2 go camping with?","Did they see any animals?","Why might camping in nature be a memorable family activity?"],
"40": ["Did Person 2 join the school team?","Is the coach strict?","Why might strict but fair coaching help a team improve?"],
"41": ["What was Person 2's project about?","Did Person 2 work with a partner?","Why might working with a partner make a project easier to complete?"],
"42": ["Did the family enjoy the food?","How long did it take to prepare?","Why might a family being impressed by cooking motivate someone to cook again?"],
"43": ["Was Person 2 nervous about the competition?","How did it go in the end?","Why might practicing regularly help reduce nervousness before a competition?"],
"44": ["Who did Person 2 see the movie with?","Was the theater crowded?","Why might a crowded theater suggest a movie is very popular?"],
"45": ["What was Person 2's role in organizing the event?","Did the event go well?","Why might helping organize an event make someone feel proud afterward?"],
"46": ["Where did Person 2 find the recipe?","Did everyone like the food?","Why might sharing a recipe with a friend help them try cooking too?"],
"47": ["How often does Person 2 train for the tournament?","Is Person 2 feeling ready?","Why might consistent daily practice help someone feel more prepared?"],
"48": ["How long did Person 2 stay with their grandparents?","Did they eat a lot of food?","Why might visiting grandparents be a relaxing way to spend time?"],
"49": ["What kind of work did Person 2 do while volunteering?","Would Person 2 volunteer again?","Why might volunteering feel rewarding even without payment?"],
"50": ["What is the teacher like this year?","Has Person 2 made new friends?","Why might making new friends in a class help someone feel more comfortable?"]
};

if (typeof module !== 'undefined' && module.exports) module.exports = QUESTIONS_LONG_A2;
