/**
 * texts-b2-new.js
 * Additional B2 reading texts — IDs 141–160
 * ~400–500 words each. New topics expand the original set.
 * window.B2TextsNew / ES export: { texts, getTopics, getByTopic, getRandom }
 */

const texts = [
  {
    id: 141, title: "The Architecture of Inequality: Housing and Social Mobility", topic: "housing and home", level: "B2", wordCount: 448,
    text: `Housing is rarely discussed simply as a matter of shelter. Where we live shapes almost every dimension of our lives — the schools our children attend, the social networks we inhabit, our exposure to environmental hazards, our access to employment, and even our life expectancy. Housing is, in this sense, one of the primary mechanisms through which social advantage and disadvantage are spatially organized and reproduced across generations.

In many high-income countries, the second half of the twentieth century saw the expansion of homeownership as a vehicle for wealth accumulation. Rising property values, combined with mortgage interest tax deductions and other policy incentives, transformed housing from a consumer good into an investment asset. For those who entered the property market early and in the right locations, the returns have been extraordinary. For those who did not — whether because of insufficient income, racial discrimination in lending, or simple misfortune of timing — the same period has involved being on the wrong side of a widening wealth gap.

The consequences of housing unaffordability extend well beyond the individuals directly priced out of homeownership. High housing costs in productive urban areas create significant barriers to economic mobility. Workers who cannot afford to live near the jobs most suited to their skills either accept lower wages or face crushing commute costs. Young people whose parents cannot help them with a deposit are increasingly unable to establish themselves in the cities where opportunities are concentrated. The intergenerational transfer of housing wealth has become one of the most significant drivers of inequality in several wealthy countries — a form of advantage that is almost entirely inherited rather than earned.

Gentrification — the process by which capital and relatively affluent residents move into formerly low-income urban neighborhoods — is perhaps the most visible and contested dimension of these dynamics. The improvements to physical environments, the reduction in some forms of crime, and the increase in economic activity that gentrification can bring are real. So is the displacement of long-established communities who are priced out by rising rents and the disappearance of affordable commercial spaces. The debate about who ultimately benefits from urban regeneration and who bears its costs is unresolved.

Public policy responses to housing affordability have been varied and their effectiveness is actively debated. Rent controls, inclusionary zoning requirements, social housing construction, and land value taxes have all been proposed and in some places implemented with varying degrees of success. The political economy of housing is extremely challenging, because in many democracies a significant proportion of voters are homeowners whose financial interests lie in maintaining or increasing property values.

What the evidence suggests with some consistency is that housing policy cannot be separated from broader questions of land use, planning, taxation, and the distribution of economic opportunity. Treating it as a purely technical question — of supply and demand, of construction rates and mortgage markets — obscures the fundamentally political choices that determine who is able to find a secure place to live.`
  },
  {
    id: 142, title: "The Ethics of Fashion", topic: "clothing and fashion", level: "B2", wordCount: 451,
    text: `The garment you are wearing right now has a biography. Before it reached your body, it was designed somewhere, the raw material from which it is made was grown or synthesized somewhere else, it was cut and sewn by workers in a factory — most likely in Bangladesh, Vietnam, Cambodia, or another country where labor costs are low — and it travelled, probably by ship, across one or more oceans. Each stage of this journey has an environmental footprint and involves human labor whose conditions vary enormously. When we buy a piece of clothing for five euros, we are purchasing the output of this entire chain. The question of what we owe to the people and environments involved is one that most of us find easier to avoid than to answer.

The scale of the fashion industry makes this avoidance understandable but increasingly difficult to sustain. Fashion is the second most polluting industry in the world after oil. The production of synthetic fibers releases petrochemicals into waterways. Cotton, one of the world's most widely grown crops, is one of its most pesticide-intensive. The dyeing and finishing of fabrics is responsible for approximately twenty percent of the world's clean water pollution. These are not peripheral effects of an otherwise benign industry; they are structural features of how clothes are produced at the scale the market demands.

The human dimension is equally difficult to look away from. The death of over 1,100 workers in the collapse of the Rana Plaza factory complex in Dhaka in 2013 created a brief global reckoning with the conditions in which most of the world's clothing is produced. In the years since, there have been improvements in safety inspections at some factories and some consolidation of supply chain transparency commitments among major brands. But the economic logic that produces poverty wages, excessive working hours, union suppression, and dangerous conditions — the need to produce ever more at ever lower cost — has not fundamentally changed.

Consumer responses to these realities exist on a spectrum. At one end is deliberate ignorance: the choice not to investigate too closely, to treat clothing as a disposable consumer category, and to take advantage of the extraordinarily low prices that the current system makes possible. At the other end is the kind of comprehensive ethical audit of one's own wardrobe that requires significant time, money, and information that most people do not have access to.

Between these extremes, a more realistic and arguably more honest position acknowledges the structural nature of the problem — that individual consumer choices, while not irrelevant, cannot resolve a systemic issue that requires regulatory intervention at the level of trade law, labor rights, and environmental standards. This does not mean individual choices are meaningless. It means that treating them as the primary solution is a form of moral convenience that lets governments and corporations off the hook.`
  },
  {
    id: 143, title: "The Construction of Historical Memory", topic: "history", level: "B2", wordCount: 453,
    text: `Every nation tells stories about its past, and these stories — what is included, what is omitted, what is celebrated, and what is mourned — are not simply the product of disinterested historical inquiry. They are political constructions, shaped by the interests, anxieties, and self-images of those who hold institutional authority at the time of their telling. The history taught in schools, commemorated in monuments, and encoded in national holidays is always, to some degree, an official history — a managed account of the past designed to produce particular effects in the present.

This does not mean that all historical narratives are equally valid or that objective historical inquiry is impossible. It means that the question of which narratives become official — which are funded, taught, carved in stone, and celebrated with public holidays — is a political question, and examining it reveals a great deal about the power structures of a given society.

The treatment of colonial history in former European imperial nations provides one of the clearest examples. For most of the twentieth century, the history of empire was taught in British, French, Spanish, and Portuguese schools primarily as a story of civilizing achievement and territorial exploration, with the violence, exploitation, and cultural destruction that accompanied it largely absent from the curriculum. The experiences of colonized peoples — their agency, their resistance, their suffering, their perspectives on the encounter — were either invisible or filtered through the lens of the colonizer.

The challenges to these official narratives that have intensified in recent decades — through the work of postcolonial scholars, through advocacy movements for the removal of colonial monuments, through demands for curriculum reform — are fundamentally arguments about whose experiences are counted as historically significant and whose are not. These are not merely debates about accuracy, though accuracy matters. They are debates about recognition, about which communities' histories are considered to belong to the national story.

Parallel debates are occurring in many contexts: over how the United States teaches the history of slavery and segregation, over how Japan addresses its conduct in World War Two, over how Germany has grappled with the Holocaust in comparison with other nations' treatment of similar historical atrocities.

What distinguishes societies that engage productively with difficult history from those that do not seems to be a combination of political leadership willing to initiate honest reckoning, civic institutions capable of sustaining complex and painful public conversations, and an educational culture that treats historical inquiry as a critical intellectual practice rather than a civic indoctrination exercise.

The goal is not collective guilt, which is both philosophically confused and psychologically counterproductive. It is something more demanding: an honest accounting that neither erases past harms nor reduces the present entirely to the past.`
  },
  {
    id: 144, title: "The Neuroscience of Language", topic: "language and communication", level: "B2", wordCount: 449,
    text: `Language is so central to human experience that it can be difficult to imagine what thinking would be like without it. We use language to reason, to remember, to plan, to communicate, to construct identity, and to create meaning. The question of how the brain produces and comprehends language — one of the most complex behaviors in the known universe — has occupied neuroscientists, linguists, and philosophers for well over a century.

For much of the twentieth century, language was understood to be localized to a small number of specific brain regions. Broca's area, in the left frontal lobe, was associated with speech production after the French physician Paul Broca described patients who had lost the ability to speak following damage to this region. Wernicke's area, in the left temporal lobe, was associated with language comprehension following similar observations by Carl Wernicke. Together, these regions formed the basis of what was known as the classical model of language.

Advances in brain imaging technology over the past three decades have significantly complicated and enriched this picture. Language processing turns out to be far more distributed across the brain than the classical model suggested, involving extensive networks in both hemispheres, with particularly dense connections between frontal, temporal, and parietal regions. Different aspects of language — phonological processing, syntactic parsing, semantic understanding, pragmatic interpretation — appear to recruit somewhat different but heavily overlapping networks.

The relationship between language and thought is one of the most philosophically and empirically contested questions in cognitive science. A strong version of the "linguistic relativity" hypothesis — associated with Benjamin Lee Whorf — holds that the language we speak fundamentally shapes what we are able to think and perceive. This claim, in its strongest form, has not been supported by experimental evidence. But a more moderate version — that the specific categories, distinctions, and structures that a language provides influence habitual patterns of thought and attention — has received more experimental support, particularly in areas such as color perception, spatial reasoning, and the representation of time.

The existence of bilingualism and multilingualism provides a fascinating natural experiment. People who speak two or more languages fluently appear to maintain their languages using overlapping but distinguishable neural networks, and the experience of managing multiple language systems appears to have cognitive effects beyond language itself. Some research suggests that lifelong bilingualism may delay the onset of dementia symptoms, though the mechanism is debated.

What the neuroscience of language is revealing is not that language is located in a place but that it is a process — a dynamic, distributed, constantly active engagement between the brain, the body, the social world, and the acoustic or written signals through which meaning is transmitted and constructed.`
  },
  {
    id: 145, title: "The Green Revolution and Its Aftermath", topic: "agriculture and farming", level: "B2", wordCount: 454,
    text: `In the decades following World War Two, the world faced what many observers considered an imminent catastrophe. Global population was growing rapidly, and projections suggested that food production could not keep pace. Famine on a massive scale seemed possible, perhaps inevitable.

What followed instead was the Green Revolution — a transformation of agricultural productivity achieved through the development and widespread adoption of high-yielding crop varieties, synthetic fertilizers, pesticides, and irrigation. Beginning in Mexico in the 1940s and 1950s under the direction of agronomist Norman Borlaug, the approach spread to South Asia, sub-Saharan Africa, and beyond. Between 1960 and 1990, global cereal production doubled. The worst predictions of mass famine did not materialize. Borlaug received the Nobel Peace Prize in 1970.

The achievements of the Green Revolution were real and substantial. It saved hundreds of millions of lives. But its costs and limitations — inadequately acknowledged at the time and in much subsequent popular discussion — were also real and substantial, and they continue to shape the agricultural challenges of the present.

The high-yielding varieties that drove the revolution were not well adapted to the conditions of all regions, and required reliable irrigation, fertilizer inputs, and pest management to achieve their potential. In regions with variable rainfall, poor soils, or limited access to inputs, the benefits were uneven. The focus on a small number of high-yielding varieties also accelerated the loss of genetic diversity in crop plants — traditional varieties that had been selected over millennia for local adaptability were abandoned and often lost.

The intensive use of synthetic nitrogen fertilizer, while dramatically increasing yields, created its own environmental cascade. Nitrogen runoff from agricultural land is a leading cause of aquatic dead zones — regions of ocean so depleted of oxygen by algal blooms fed by fertilizer runoff that they cannot support marine life. The Haber-Bosch process, by which synthetic nitrogen is produced, accounts for roughly two percent of global energy consumption and a significant proportion of greenhouse gas emissions.

The social consequences were also mixed. The capital-intensive nature of Green Revolution agriculture favored larger landowners who could afford inputs and irrigation. In some regions, the transformation accelerated the displacement of small farmers and contributed to rural-to-urban migration.

These critiques do not negate the revolution's achievements. They do, however, complicate any simple narrative of technological salvation and suggest that the agricultural challenges of the current era — feeding a growing population while reversing the environmental damage of the past century — will require approaches that are simultaneously more productive and more ecologically sophisticated. What worked once, under one set of conditions, with a particular understanding of costs and benefits, is not a template that can be straightforwardly applied again.`
  },
  {
    id: 146, title: "Dark Matter and the Limits of Knowledge", topic: "science and discovery", level: "B2", wordCount: 452,
    text: `One of the most unsettling features of modern physics is the recognition that the matter we can see — the stars, galaxies, planets, and everything else that interacts with light — constitutes only about five percent of the total content of the universe. The remaining ninety-five percent consists of entities called dark matter and dark energy, neither of which has ever been directly detected, whose nature remains entirely unknown, and which have been inferred to exist purely from their gravitational effects on the things we can observe.

Dark matter was first proposed in the 1930s by the Swiss astronomer Fritz Zwicky, who noticed that the galaxies in the Coma Cluster were moving too fast to be held together by the visible mass they contained. Something extra had to be providing gravitational force. Over the subsequent decades, evidence accumulated from multiple independent lines of observation — the rotation curves of spiral galaxies, the bending of light by galactic clusters, and the large-scale structure of the universe — all pointing to the existence of large quantities of non-luminous matter.

What dark matter actually is remains one of the deepest open questions in science. Dozens of candidate particles have been proposed by theoretical physicists. The most widely studied are weakly interacting massive particles, or WIMPs, which would interact with ordinary matter only through gravity and the weak nuclear force. Experiments involving detectors placed deep underground to shield them from cosmic rays have been searching for WIMP interactions for decades without success, leading some physicists to conclude that WIMPs do not exist as predicted and that alternative candidates must be considered.

Dark energy is, if anything, even more mysterious. First inferred in 1998 from observations that the expansion of the universe is accelerating rather than decelerating — as gravity alone would predict — it appears to constitute approximately seventy percent of the universe's total energy content and to act as a kind of anti-gravitational force, pushing space apart on the largest scales. No theoretical framework fully accounts for it, and its observed value differs from theoretical predictions by a factor so enormous that it has been described as the worst prediction in the history of physics.

What dark matter and dark energy represent is not merely a technical puzzle awaiting a technical solution. They are reminders of something that scientific culture can be prone to forget: that the map we have drawn of reality is a small and provisional sketch of an immensely larger territory. The confidence with which physics predicts the behavior of the observable universe — and that confidence is genuinely warranted by extraordinary predictive success — should not be mistaken for comprehensive understanding. We are, on the largest scales, navigating largely in the dark.`
  },
  {
    id: 147, title: "The Financialization of Everything", topic: "business and money", level: "B2", wordCount: 449,
    text: `Over the past four decades, a transformation has occurred in the structure of advanced economies that has been variously described, analyzed, and contested but is rarely given a single coherent name in public discourse. The transformation is this: an ever-larger proportion of economic activity — and of the profits generated by that activity — has migrated from the production of goods and services toward the management of financial assets. Economists call this process "financialization," and its consequences pervade almost every aspect of contemporary economic and social life.

The most immediate manifestation is the growth of the financial sector itself. In the United States, financial services accounted for approximately ten percent of corporate profits in 1950. By the 2000s, that figure had risen to approximately forty percent, even as the sector employed a relatively small proportion of the total workforce and produced no physical goods. This expansion was driven by deregulation, by the invention of increasingly complex financial instruments, by the globalization of capital flows, and by the intellectual prestige of economic theories that treated financial markets as efficient allocators of resources.

But financialization extends beyond the financial sector into the behavior of companies in other sectors. The rise of "shareholder value" as the dominant framework for corporate governance encouraged managers to prioritize short-term returns to shareholders over long-term investment in productive capacity, workforce development, and research. Companies began directing a larger share of their profits toward share buybacks and dividends — which boost shareholder returns — rather than toward capital investment. This pattern is associated with the erosion of manufacturing capacity in several high-income countries.

Housing, education, healthcare, and infrastructure have all undergone varying degrees of financialization — coming to be treated less as social goods and more as financial assets or investment vehicles. This shift has profound implications for access and affordability. When housing is primarily an asset class, the interests of investors and those of residents seeking shelter are in direct tension. When student debt is securitized and sold to investors, the financial interests in maintaining high tuition levels acquire additional institutional weight.

The political economy of financialization is deeply entangled with the rise of inequality in high-income countries. The ownership of financial assets is highly concentrated; as the financial sector's share of the economy has grown, so have the incomes and wealth of those who own substantial quantities of financial assets. The erosion of labor's bargaining power — through deindustrialization, weakened union rights, and the growing use of automation and contract labor — is in part a consequence of the same structural shifts.

None of this implies that finance itself is parasitic or harmful. Credit markets, insurance, and efficient allocation of investment capital are genuine contributions to economic welfare. The question is one of proportion, governance, and the distribution of the gains — questions that are, in the end, political rather than purely economic.`
  },
  {
    id: 148, title: "The Sociology of Crime", topic: "crime and justice", level: "B2", wordCount: 451,
    text: `The persistence of crime across all human societies, regardless of culture, epoch, or institutional arrangement, suggests that its causes are not simply matters of individual moral failure but are rooted in the structural conditions of social life itself. This is the central insight of the sociological tradition in criminology, which emerged in the late nineteenth and early twentieth centuries as an alternative to purely individualistic or biological explanations of criminal behavior.

Émile Durkheim, one of the founding figures of modern sociology, made the provocative argument that a certain level of crime is not merely an unfortunate byproduct of social life but is, in a sociological sense, normal — and even functional. Societies define themselves partly through the distinction between acceptable and unacceptable behavior; the punishment of wrongdoing reinforces collective moral boundaries and strengthens social solidarity. A society with no crime at all would require such a level of conformity and social control that the resulting rigidity would inhibit the social and moral evolution that allows societies to adapt over time.

Robert Merton's strain theory, developed in the mid-twentieth century, offered a more structural account of the distribution of crime within societies. Merton observed that societies typically hold out certain culturally valued goals — wealth, success, status — as available to all members, while the legitimate means to achieve those goals are in practice unequally distributed. People in social positions where legitimate pathways to success are blocked experience a "strain" between cultural aspiration and structural reality. Crime, in this framework, is one rational response to that strain.

The implications of this analysis are politically significant. If crime is substantially a product of structured inequality and blocked opportunity rather than individual deficiency, then strategies focused exclusively on punishment and incarceration are addressing the symptoms while leaving the causes intact. The United States — which has the world's highest per capita incarceration rate — provides a long-running natural experiment in the limits of a carceral approach to crime reduction.

This does not mean that individual agency, moral development, and the deterrent effect of consequences are irrelevant. It means that they operate within structural conditions that profoundly shape the choices available to individuals, and that changing those conditions is likely to be more effective at reducing crime than any amount of additional punishment.

The criminal justice systems of most countries are built primarily around punishment, deterrence, and incapacitation. But a growing body of evidence suggests that approaches focused on rehabilitation, on addressing the social determinants of crime, and on reintegrating offenders into society produce better outcomes — for public safety, for victims, and for the individuals who pass through the system — than pure incarceration. The gap between what evidence suggests works and what political systems fund and implement remains, in most countries, very wide.`
  },
  {
    id: 149, title: "Embodied Cognition", topic: "psychology", level: "B2", wordCount: 448,
    text: `For most of the history of Western philosophy and, subsequently, cognitive science, the mind was understood to be housed in the brain and to process information largely independently of the body that carried it around. Descartes' famous formulation — "I think, therefore I am" — encapsulates a dualistic tradition in which the thinking self is fundamentally distinct from the physical body. The cognitive revolution in psychology in the mid-twentieth century, while rejecting Cartesian dualism in some respects, largely preserved the model of the brain as an information-processing device that receives input from the body and environment and outputs behavior.

The embodied cognition framework, which emerged as a significant intellectual movement in the 1980s and 1990s, proposes a fundamentally different picture. On this view, cognition is not simply computation happening in the brain; it is a process that is intrinsically shaped by the structure of the body, by the body's specific sensorimotor capabilities, and by the environment in which the body is embedded. Thinking is not done by the brain in isolation; it is done by a brain inside a body inside a world.

The empirical evidence for this view is diverse and sometimes surprising. People asked to describe concepts related to warmth tend to use words with warmer connotations when they are physically holding a warm cup of coffee. Subjects who nod their heads vertically while listening to an argument are more likely to agree with it than those who are shaking their heads horizontally — the motor action associated with agreement apparently reinforces assent. Metaphors of physical force, weight, texture, and spatial orientation are not merely decorative elements of abstract language; they appear to activate sensorimotor brain regions associated with the corresponding physical experiences.

The concept of "affordances," developed by psychologist James Gibson, captures another dimension of embodied cognition. An affordance is a property of an environment or object that invites or allows a particular action. A chair "offers" sitting; a handle "offers" grasping. Our perception of the world is not, on this view, the passive registration of neutral sensory data; it is the active detection of action possibilities for a body with specific capabilities. A doorway that is "narrow" for one person may be "wide" for another — the perception is not of an objective property but of a relation between environment and body.

These findings have practical implications for education, for the design of therapeutic interventions, and for our understanding of what is lost when increasingly abstract, screen-mediated experience displaces embodied, physical engagement with the world. The concern is not merely nostalgic. If cognition is genuinely embodied, then the impoverishment of physical experience may have cognitive consequences that purely information-based compensations cannot fully address.`
  },
  {
    id: 150, title: "The Anthropocene: Human Beings as Geological Force", topic: "nature", level: "B2", wordCount: 453,
    text: `Geologists divide Earth's history into named epochs defined by characteristic physical and biological signatures preserved in rock, sediment, and ice. For the past 11,700 years, we have lived in the Holocene — a period of unusual climatic stability that, many scientists now argue, is itself partly responsible for the conditions that enabled the development of agriculture, settled civilization, and eventually the global industrial economy.

A growing consensus among Earth scientists holds that human activity has now so comprehensively altered the physical, chemical, and biological systems of the planet that we have effectively ended the Holocene and inaugurated a new epoch: the Anthropocene, the "age of humans." The proposal has not yet been formally ratified by the relevant international bodies, but the underlying empirical argument — that humanity has become a geological force — has achieved broad scientific acceptance.

The signatures of the Anthropocene that will be legible in the geological record to observers thousands or millions of years from now are numerous and distinctive. The redistribution of carbon from geological deposits to the atmosphere through fossil fuel combustion has altered the chemical composition of both the atmosphere and the ocean on a scale and at a speed with no precedent in the geological record of the past fifty-six million years. The global spread of artificial materials — concrete, plastics, aluminum alloys — means that every stratum of sediment deposited since approximately 1950 contains material that does not exist in nature. The systematic extermination of wild megafauna and the replacement of wild landscapes with agricultural monocultures has produced a biological impoverishment that will appear, in the fossil record, as a mass extinction event comparable to those caused by asteroid impacts.

The naming of the Anthropocene is not merely a scientific exercise. It carries significant implications for how we understand our situation and our responsibilities. To acknowledge that we have become a geological force is to acknowledge that the natural world is no longer an independent backdrop to human history but something that has been incorporated into it — that what happens to nature now happens by human choice, including the choice not to intervene.

This framing generates both paralysis and possibility. The paralysis comes from the sheer scale of the transformation required to stabilize the systems we have destabilized. The possibility comes from the same recognition: if humans created these problems, humans — with sufficient knowledge, coordination, and political will — can take responsibility for addressing them.

Whether the Anthropocene becomes a story of civilizational recklessness followed by catastrophe or of unprecedented adaptive ingenuity is a question that will be answered by the cumulative choices of the people alive in the decades ahead.`
  },
  {
    id: 151, title: "Populism and the Crisis of Liberal Democracy", topic: "politics and society", level: "B2", wordCount: 451,
    text: `Liberal democracy — a system combining democratic elections with constitutional protections for individual rights, the rule of law, and the independence of institutions — has been the dominant political framework of wealthy nations for most of the past century. Its foundations were shaken by the catastrophes of totalitarianism in the twentieth century, but it emerged from those challenges strengthened, spreading to new regions as former dictatorships and communist states transitioned toward democratic governance. By the end of the twentieth century, the political scientist Francis Fukuyama was prepared to argue that liberal democracy represented the "end of history" — the final form of human political organization.

The first decades of the twenty-first century have severely complicated this confidence. Across diverse contexts — in Hungary and Poland in Europe, in Brazil, in India, and most prominently in the United States — political movements typically described as populist have achieved power while challenging institutional norms that liberal democracy depends upon: the independence of courts and media, the integrity of electoral processes, protections for minority rights, and the legitimacy of political opposition.

Populism is a notoriously difficult concept to define precisely, partly because movements described as populist vary greatly in their specific programs and ideologies. What they typically share is a rhetorical structure that divides society between a virtuous and culturally homogeneous "people" and a corrupt, alien, or parasitic "elite," and that claims to express the authentic will of the people against the machinations of this elite. This structure is inherently anti-pluralist: it treats political opposition and institutional constraints as illegitimate interference with the popular will rather than as features of a well-functioning democratic system.

The causes of populism's current resurgence are themselves disputed, but several candidate explanations have significant empirical support. The economic dislocations produced by globalization and technological change have left large communities with a well-grounded sense that the political mainstream failed to represent their interests or acknowledge their losses. The hollowing out of intermediate civic institutions — trade unions, local political parties, religious organizations — has removed the structures through which diverse interests were historically aggregated and represented. Cultural and demographic change has created anxieties about identity and belonging that mainstream politics has been ill-equipped to address.

Understanding populism as a symptom rather than simply a cause — as evidence of genuine failures within liberal democratic systems that need to be addressed rather than simply pathologies to be overcome — is difficult for those who identify with the institutions under challenge. But it is probably the more honest and ultimately more useful analytical starting point.

Liberal democracy faces a genuine test. Its defense requires not only institutional resilience but a serious reckoning with the conditions that made its challengers appear credible to so many of its own citizens.`
  },
  {
    id: 152, title: "The Paradox of Tolerance", topic: "politics and society", level: "B2", wordCount: 448,
    text: `Political philosophy rarely generates genuinely practical puzzles, but the paradox of tolerance — identified by the philosopher Karl Popper in his 1945 work "The Open Society and Its Enemies" — is one that has become urgently relevant in contemporary democratic life.

Popper's argument is disarmingly simple: a society that is perfectly tolerant of all views and behaviors will eventually be destroyed by those who use that tolerance to promote intolerance. If a society grants unrestricted freedom of expression and political organization to movements that are fundamentally committed to eliminating the conditions of free society — to abolishing elections, eliminating the rights of minorities, silencing opposition — then those movements may, if they gain sufficient power, do exactly that. Perfect tolerance therefore undermines itself. The tolerant society must be prepared to be intolerant of intolerance, or it will cease to be tolerant.

Popper's own formulation was careful and limited. He did not argue that intolerant views should be suppressed by force; rather, he argued that the tolerant society is justified in treating them as outside the domain of rational discourse — as not entitled to the normal protections of free expression — if they resort to fomenting violence or actively working to suppress the freedoms of others. The threshold he set was high, and he explicitly preferred non-suppressive responses where possible.

The contemporary relevance of this argument is evident in debates about online content moderation, the platform policies of social media companies, the invitation of speakers to university campuses, and the legal limits of political advocacy. In each context, a version of the same question recurs: where does the legitimate scope of tolerance end, and what justifies drawing a line?

These questions are made more difficult by the significant disagreement that exists about what actually constitutes intolerance. In a polarized political environment, each side is inclined to perceive the other's positions as not merely wrong but as beyond the pale of legitimate democratic discourse. The accusation of intolerance is itself a political weapon, and the paradox of tolerance can be invoked to justify suppression of views that do not, on close examination, actually threaten the foundations of free society.

The practical resolution Popper pointed toward — drawing the line at actual advocacy of violence and active suppression of others' rights, while maintaining broad tolerance elsewhere — requires institutions capable of making these distinctions carefully and consistently, with procedural legitimacy and without partisan capture.

These institutional requirements are exactly what populist movements typically challenge. The paradox of tolerance does not resolve itself; it demands ongoing institutional judgment and political courage — the willingness to draw and defend principled distinctions in the face of both genuine threats and politically motivated accusations.`
  },
  {
    id: 153, title: "Art, Censorship, and the State", topic: "art and creativity", level: "B2", wordCount: 450,
    text: `The relationship between artistic expression and political authority is ancient and consistently contentious. From Plato's prescription that poets be expelled from the ideal republic because they appeal to the passions rather than reason, to the Index Librorum Prohibitorum maintained by the Catholic Church for four centuries, to the Socialist Realism imposed by Soviet cultural authorities on artists from the 1930s onward, the impulse of concentrated authority to manage artistic expression runs deep in human institutional history.

The grounds offered for censorship have varied considerably across historical contexts. Religious censorship aimed to protect believers from heretical doctrine and to reinforce the authority of ecclesiastical interpretation. Political censorship has aimed to prevent subversion, protect state secrets, and maintain the conditions of social order and ideological coherence that particular regimes required. Moral censorship has aimed to protect social norms and, in particular, to shield children and vulnerable individuals from potentially harmful material.

Liberal democratic theory provides relatively clear answers to some of these arguments. The principle of free expression — grounded in values of individual autonomy, the epistemological case for open inquiry articulated by John Stuart Mill, and the democratic case for political pluralism — has been institutionalized in constitutional protections across most liberal democracies. On this framework, the harm caused by suppressing speech is typically greater than the harm caused by tolerating it, because free inquiry is necessary for truth to emerge and because the power to suppress will inevitably be abused.

But the boundaries of this principle have always been contested in practice. Defamation, fraud, incitement to violence, child exploitation material, national security information — all have been recognized, even in the most speech-protective legal systems, as categories where the costs of unrestricted expression outweigh its benefits. These exceptions reveal that even the most principled defenders of free expression are, in practice, accepting that some limits are warranted; the argument is about where the line should fall, not whether any line exists.

The digital environment has introduced new pressures that traditional frameworks are ill-equipped to address. The amplification effects of social media — by which even marginal voices can reach millions — have raised the stakes of speech in ways that Enlightenment-era defenses of free expression did not anticipate. The question of whether private platform companies, when they exercise enormous influence over public discourse, bear some of the obligations traditionally associated with public institutions is one that legislators and courts across the world are still working to resolve.

What historical experience teaches, at minimum, is that the power to censor is almost always eventually turned against forms of expression that, in retrospect, we recognize as valuable. The chilling effect of censorship on dissent, on creativity, and on the forms of criticism that allow institutions to be held to account is a cost that should never be treated as trivial.`
  },
  {
    id: 154, title: "The Biology of Aging", topic: "medicine and body", level: "B2", wordCount: 447,
    text: `Aging is so universal and so fundamental to the experience of living organisms that it can seem like a simple fact of nature rather than a biological process with discoverable causes and potentially modifiable mechanisms. But the biology of aging has become one of the most active and well-funded areas of biomedical research, driven by a convergence of practical urgency — aging populations placing increasing demands on healthcare systems — and genuine scientific progress in understanding what aging actually is at the cellular and molecular level.

The most established biological theories of aging focus on the accumulation of damage at the cellular level over time. DNA is constantly being damaged by radiation, metabolic byproducts, and chemical exposure, and while repair mechanisms exist, they are imperfect. As cells divide repeatedly, the protective caps at the ends of chromosomes — called telomeres — shorten progressively. When they become too short, cells can no longer divide safely and either enter a state of permanent growth arrest (cellular senescence) or undergo programmed death. The accumulation of senescent cells, which are metabolically active and secrete inflammatory signals, is increasingly associated with many of the tissue changes characteristic of aging.

Mitochondria — the cellular organelles responsible for producing energy — appear to play a particularly important role in the aging process. Mitochondrial function declines with age, and the free radicals produced as byproducts of energy production damage cellular components. The dysregulation of cellular energy metabolism is implicated in a wide range of age-related diseases.

Epigenetic changes — alterations in how genes are expressed without changes to the underlying DNA sequence — also accumulate with age and are increasingly recognized as significant drivers of the aging phenotype. The discovery of "epigenetic clocks" — mathematical models that can predict chronological age from patterns of DNA methylation with remarkable accuracy — has provided new tools for studying aging and for testing potential interventions.

Research in model organisms has demonstrated that aging can be substantially slowed through genetic, dietary, and pharmacological interventions. Caloric restriction — reducing food intake without malnutrition — extends lifespan in organisms from yeast to primates. Drugs that target nutrient-sensing pathways associated with aging, most prominently rapamycin, have extended lifespan in mice even when administered relatively late in life. These findings have generated significant excitement about the possibility of treating aging as a medical condition.

The philosophical and ethical dimensions of significantly extending human lifespan are complex and incompletely addressed. Questions about the equitable distribution of longevity interventions, the social implications of compressed versus extended generational turnover, and what a meaningful longer life would actually require are not questions that biology alone can answer.`
  },
  {
    id: 155, title: "Games, Play, and the Civilizing Process", topic: "games and hobbies", level: "B2", wordCount: 450,
    text: `Johan Huizinga's "Homo Ludens," published in 1938, made a provocative argument that has been debated and refined ever since: that play is not merely a feature of human life but one of its foundational structures. On Huizinga's account, human culture — law, art, religion, warfare, philosophy — does not emerge first as serious, utilitarian activity and then incorporate playful elements; rather, it arises within the domain of play. Play is prior to culture; culture is, in many of its most significant forms, an elaboration of play.

This claim is difficult to evaluate precisely because "play" and "game" are resistant to clean definition. What distinguishes play from non-play? Huizinga's own criteria — that play is voluntary, spatially and temporally bounded, uncertain in outcome, unproductive in the sense of creating no material surplus, governed by rules, and accompanied by a sense of tension and joy — are suggestive but leave significant edge cases. By these criteria, much professional sport is not quite play; nor, perhaps, is highly competitive game-playing.

The contemporary landscape of games has expanded enormously and in ways that Huizinga could not have anticipated. Digital games have become the largest entertainment industry in the world, generating more revenue than film and music combined. Competitive gaming — esports — has developed into a professional sector with dedicated venues, broadcast rights, sponsorship deals, and prize pools comparable to established physical sports. The players of the most popular competitive games train with the discipline and intensity of elite athletes.

These developments raise interesting questions about the relationship between play and work. When play becomes a profession, when leisure becomes labor, when the gaming industry appropriates the vocabulary of fun to extract financial value from addictive mechanics — is something essential to the nature of play being lost? Or is this a spurious nostalgic concern that ignores the fact that all institutionalized play has always existed in tension with the pure voluntary spirit of the playground?

The therapeutic literature on play offers a different perspective. Play therapy is a well-established clinical approach with children, and the extension of play-based approaches to adult therapeutic contexts has gathered evidence over recent decades. The protective value of play for mental health — its capacity to provide safe spaces for processing difficult experiences, for experimenting with identities and roles, and for experiencing the satisfaction of competent performance in low-stakes environments — is distinct from both its cultural significance and its commercial exploitation.

What persists across Huizinga's historical analysis, contemporary game studies, and therapeutic psychology is a common insight: that the space of play is a space of particular human freedom and creativity, which is precisely why both individuals and institutions have always been tempted to colonize it for other purposes.`
  },
  {
    id: 156, title: "The Crisis of Mainstream Journalism", topic: "politics and society", level: "B2", wordCount: 452,
    text: `The economic model that sustained mainstream journalism for most of the twentieth century — advertising revenue proportional to audience size, enabling the cross-subsidization of expensive public-interest reporting by entertainment and lifestyle content — has been disrupted to the point of near-collapse by the rise of the internet and social media. The consequences for the institutions of democratic accountability are serious and incompletely appreciated.

The disintermediation of advertising — the direct connection of advertisers with targeted audiences through digital platforms, bypassing the news organizations that had previously served as the medium — removed the financial foundation of most local and regional newspapers. The United States has lost approximately two thousand local newspapers since 2005. Entire geographic areas now have no dedicated local journalistic coverage. The phenomena documented in political science research under the label "news deserts" — communities where local government, local business, and local institutions operate without meaningful journalistic scrutiny — are expanding.

This matters for reasons that go beyond sentimental attachment to a particular media format. Investigative journalism — the time-intensive, expensive, legally risky process of documenting institutional wrongdoing — serves a democratic function that alternative information sources do not currently replicate. Social media amplifies opinion, commentary, and viral content efficiently, but it does not send reporters to city council meetings, file freedom of information requests, or develop the source relationships and institutional knowledge necessary to expose systematic corruption. The record of major investigative journalism — Watergate, the Catholic Church abuse scandals, offshore financial fraud, pharmaceutical industry misconduct — is a record of scrutiny that powerful institutions have every reason to resist and that requires dedicated professional infrastructure to sustain.

The response from existing institutions has been a combination of digital adaptation, cost-cutting, and foundation-funded nonprofit models. Some of these have been successful. The Guardian, a British newspaper, has largely survived the transition through reader support rather than digital advertising. ProPublica and similar nonprofit investigative organizations have produced significant work. But these examples are exceptions against a general background of contraction.

The deeper problem is structural. Journalism as a public good — information that benefits society regardless of whether it benefits the individual consumer in a direct, measurable way — is difficult to sustain through market mechanisms alone. Investigative reporting on municipal finance, environmental compliance violations, or police misconduct does not typically attract the audience numbers that justify its cost from a purely commercial perspective. Its value is social, not personal, and market mechanisms are poor at pricing social value.

This recognition points toward some form of public or civic subsidy for journalism as a democratic institution — an idea that has been implemented in various forms in Scandinavia and that is increasingly being discussed in countries where the commercial model has collapsed most completely.`
  },
  {
    id: 157, title: "The Body as Text: Tattoos, Dress, and the Semiotics of Self-Presentation", topic: "clothing and fashion", level: "B2", wordCount: 449,
    text: `Every human society uses the body as a surface for meaning-making — decorating, piercing, scarring, tattooing, clothing, and adorning it in ways that communicate social status, group membership, spiritual affiliation, personal history, and aesthetic sensibility. The specific forms this takes vary enormously across cultures and historical periods, but the impulse to make the body legible — to turn it into something that can be read by others and by oneself — appears to be universal.

The semiotic analysis of bodily adornment — treating the decorated body as a system of signs that carry meaning in relation to a cultural code — has produced valuable insights, but also risks a certain interpretive overconfidence. The meaning of a tattoo, a style of dress, or a hairstyle is never fully fixed or transparent. It shifts with context, with the perceiver, and over time as cultural codes evolve. A style that signals radical subcultural membership in one decade becomes mainstream fashion in the next, its original associations diluted or inverted.

The history of tattooing in Western culture illustrates this complexity well. Tattoos entered Western popular consciousness primarily through their association with sailors, convicts, and social margins — they were markers of outsider status and masculine toughness. In the late twentieth and early twenty-first centuries, they underwent a remarkable transformation, moving from the social margins to the mainstream to the point where they are now the most popular form of permanent body modification in many Western societies. Their signifying function has not disappeared, but it has become far more varied, personal, and contextually dependent.

The psychoanalytic tradition offers a different angle: that bodily adornment is not primarily communication to others but communication to oneself — a form of self-construction, of making an identity tangible and visible. People who describe getting a tattoo commemorating a significant life event often describe the motivation in terms of externalization: making something internal — grief, transformation, love, commitment — visible and permanent on the body. The tattoo is less a message to observers than a material anchor for the self.

The tension between individual expression and social readability is inherent to all bodily self-presentation. We dress partly for others — to manage the impressions we create and to signal membership in particular groups — and partly for ourselves, to project to our own reflection an image of who we wish to be. These motivations are rarely entirely separable, and their relationship changes across contexts.

What the semiotic perspective most usefully reveals is that the choices we make about how to present our bodies are choices, even when they feel automatic or natural — embedded in cultural systems of meaning that pre-date and exceed us, but animated by individual desires, histories, and experiments in identity that are irreducibly our own.`
  },
  {
    id: 158, title: "The Digital Transformation of Memory", topic: "psychology", level: "B2", wordCount: 447,
    text: `Photographs were once comparatively rare documents of significant moments. A family might take a single photograph on a major occasion — a wedding, a birthday, a holiday departure — and the physical print would be preserved, sometimes for generations, as a material record of a moment that had passed. The advent of the smartphone camera, combined with essentially unlimited digital storage, has transformed this almost beyond recognition. People now take more photographs in a year than were taken in the entire nineteenth century, and most of them are stored in digital libraries that are rarely reviewed and often lost when a device fails.

What are the cognitive consequences of this transformation? Psychologist Linda Henkel's research at Fairfield University examined whether taking photographs of objects in a museum affected participants' memory of them. The results were counterintuitive and have been widely discussed: participants who photographed objects remembered them worse — in both detail and accuracy — than those who simply looked at them. Henkel's interpretation was that the act of photographing functioned as a form of "cognitive offloading": participants transferred the responsibility for remembering to the device, reducing the processing devoted to encoding the memory.

This finding fits within a broader body of research on what has been called the "Google effect" — the tendency to remember where information can be found rather than the information itself when we know it is reliably stored externally. We are outsourcing aspects of memory to digital systems, and some researchers argue that this is continuous with the cognitive evolution that has always accompanied new memory technologies, from writing to print to digital search. On this view, the relevant question is not whether we are remembering less but whether the human-tool system as a whole is more capable than either component alone.

But there are aspects of the transformation that this relatively optimistic account may underestimate. The phenomenological dimension of memory — the experience of remembering, as distinct from the information content of what is remembered — may be affected in ways that are not captured by recall accuracy tests. Many people report that the photographs they take of experiences feel, paradoxically, less vivid as memories than experiences they did not photograph. The act of viewing through a lens may interpose a degree of distance between the person and the experience, interrupting the absorption that produces particularly rich memories.

There is also a social and relational dimension to the transformation. The shared experience of looking at physical photographs together, of narrating and selecting and constructing a shared past, was an important mode of collective memory and family identity formation. What replaces this — if anything — in the era of individual digital photo libraries that are rarely shared, rarely printed, and rarely reviewed, is an open question.`
  },
  {
    id: 159, title: "The Grammar of Power: How Language Encodes Hierarchy", topic: "language and communication", level: "B2", wordCount: 452,
    text: `Language does not merely describe social hierarchies; it participates in constructing and maintaining them. The forms of address, pronouns, vocabulary choices, and syntactic structures we use when speaking to and about other people are not neutral conveyances of information. They carry and reproduce the social distinctions of rank, gender, age, class, and institutional authority that organize human societies. Attending to this dimension of language is not a politically motivated distortion of linguistic analysis; it is an elementary observation about how language actually works.

The history of second-person pronouns in European languages provides a clear illustration. In French, vous is both the plural second-person pronoun and the formal singular form used to address strangers, superiors, and those with whom one is not intimately acquainted. Tu is the informal singular form, used between intimates, toward children, and historically toward social inferiors. The choice between the two — what linguists call the T-V distinction — encoded and performed social relationships with every utterance. Similar distinctions existed in German (du versus Sie), Spanish (tú versus usted), Italian (tu versus Lei), and historical English (thou versus you). The gradual disappearance of the informal form in standard English, leaving only you, did not eliminate social distinctions; it shifted the field on which they were performed.

The grammar of gender is a similarly revealing case. Languages differ enormously in how grammatically they encode gender distinctions. Languages with grammatical gender — in which nouns, articles, and adjectives carry gendered marking — construct a world in which the social category of gender is applied not just to people but to objects, abstractions, and activities. Research suggests that these grammatical systems influence perception: speakers of languages that gender a given noun differently tend to associate different qualities with the referent. German speakers, for whom Brücke (bridge) is feminine, use different descriptors for bridges than Spanish speakers, for whom puente is masculine.

The language of institutions — courts, parliament, medicine, academia — provides another domain where linguistic encoding of hierarchy is both systematic and consequential. The passive voice is often deployed to remove agents from descriptions of actions whose attribution would be politically uncomfortable: "Mistakes were made," "The village was destroyed." This is not accidental; it is a reliable feature of official language under conditions where accountability is being managed rather than accepted.

The asymmetries in how language is received based on the identity of the speaker are equally significant. Research in communication and sociolinguistics documents systematic differences in how identical speech acts are interpreted depending on whether the speaker is perceived as male or female, as racially dominant or subordinate, as native or non-native. The same assertion may be heard as confident expertise or arrogant overreach; the same question as genuine inquiry or hostile challenge — the semantic content is identical while the social meaning shifts with the perceived social location of the speaker.`
  },
  {
    id: 160, title: "What Do We Owe the Future?", topic: "politics and society", level: "B2", wordCount: 450,
    text: `Moral philosophy has historically been most comfortable reasoning about obligations between people who are contemporaries — those alive at the same time, capable in principle of affecting each other's interests and engaging in reciprocal relationships. The more difficult question of what obligations the living bear toward people who do not yet exist has been treated as a philosophical curiosity rather than an urgent practical matter. That has changed. The recognition that current choices about climate, biodiversity, technology, and institutions will profoundly shape the lives of billions of people who are not yet born has made intergenerational ethics one of the most pressing areas of moral and political philosophy.

The philosophical difficulty begins with the "non-identity problem," formulated by Derek Parfit. Most future people will not exist unless current people make specific choices about reproduction, settlement, and technology. Change any significant choice, and different people will be born. This means that most future people cannot be said to be harmed by current choices in the traditional sense, because if we had chosen differently, they would not exist at all. A world with severe climate change contains people who would not have existed in a world that avoided it; those specific people cannot coherently claim to have been wronged by choices that were a condition of their existence.

Parfit and subsequent philosophers have argued that this puzzle does not dissolve our obligations to the future. Even if we cannot coherently claim to harm specific future people, we can recognize that creating conditions in which billions of people live constrained, suffering lives is wrong in a morally significant sense — that there is a meaningful difference between leaving the world roughly as we found it and leaving it comprehensively damaged.

The political philosophy of future generations is complicated by the fact that standard democratic mechanisms give future people no vote and no voice. Their interests are formally unrepresented in the institutions that make the decisions with the greatest long-term consequences. Several countries and international bodies have experimented with formal institutions for future representation — commissioners or ombudspersons charged with advocating for long-term interests in current policy processes — but these institutions are typically advisory, underfunded, and easily ignored when they conflict with immediate political imperatives.

The discount rate — the degree to which future costs and benefits are weighted less heavily than present ones in economic analyses — is one of the most consequential technical parameters in climate economics. Small changes in discount rates produce dramatically different assessments of how much current sacrifice is warranted to avert future harm. These are not merely technical choices; they embed moral judgments about the relative weight of present and future people's interests that should be explicit but are typically obscured by the formalism of economic modeling.

The question of what we owe the future is, at bottom, a question about whether we see ourselves as links in a chain of generations or as sovereign consumers of a shared inheritance.`
  },
];

function getTopics() { return [...new Set(texts.map(t => t.topic))]; }
function getByTopic(topic) { const q = topic.toLowerCase(); return texts.filter(t => t.topic.toLowerCase().includes(q)); }
function getRandom() { return texts[Math.floor(Math.random() * texts.length)]; }

export { texts, getTopics, getByTopic, getRandom };
export default texts;
if (typeof window !== 'undefined') window.B2TextsNew = { texts, getTopics, getByTopic, getRandom };
