const QUESTIONS_LONG_A1 = {
"1": ["What is Person 1's name?","What food and drink does Person 2 like?","Why do people usually ask 'What's your name?' when they first meet?"],
"2": ["Where does Person 2 live?","What time does Person 2 leave home?","Why might someone prefer walking to school instead of taking a bus?"],
"3": ["What pet does Person 2 have?","What is the pet's name and where does it like to play?","Why might someone want to know if a pet is friendly before visiting?"],
"4": ["What is Person 2's favorite subject?","What time does the class start?","Why might a student say a subject is 'fun and easy'?"],
"5": ["What sport does Person 2 play?","Who does Person 2 play with?","Why might playing a sport with family be more enjoyable than playing alone?"],
"6": ["What day is it in the conversation?","What time does Person 2's class start?","Why might someone ask 'What day is it?' before checking their class schedule?"],
"7": ["What is the weather like?","Where does Person 2 like to stay in this weather?","Why might someone prefer staying inside during certain weather?"],
"8": ["What does Person 1 offer Person 2?","What does Person 2 say about the food?","Why is it polite to say 'yes, please' when offered something?"],
"9": ["How old is Person 2?","What season is Person 2's birthday in?","Why might birthdays with family feel more special than birthdays alone?"],
"10": ["What color does Person 2 like?","Where did Person 2 get the object?","Why might someone care about the color of something they buy?"],
"11": ["Does Person 2 have a brother or sister?","Is the sibling older or younger than Person 2?","Why might siblings who are close in age play together often?"],
"12": ["What time does Person 2 wake up?","What does Person 2 eat for breakfast?","Why is breakfast often considered an important meal?"],
"13": ["What kind of movies does Person 2 like?","Who does Person 2 watch movies with?","Why might watching movies with family be a common weekend activity?"],
"14": ["Where is Person 2's family member?","What is she doing?","Why might someone ask where a family member is before joining them?"],
"15": ["What is for lunch today?","Who does Person 2 eat lunch with?","Why might eating lunch with friends make school more enjoyable?"],
"16": ["What sport does Person 2 like?","Does Person 2 play the sport too?","Why might a fan of a sport also want to play it themselves?"],
"17": ["What is the weather like today?","Where is Person 2 going?","Why might someone need a jacket even on a nice day?"],
"18": ["What hobby does Person 2 like?","When does Person 2 do this hobby?","Why might hobbies be more fun when shared with family?"],
"19": ["What day is the subject class?","What time does the class happen?","Why might a student feel excited about a specific class?"],
"20": ["What place do they want to go to?","What day do they plan to go?","Why is it helpful to agree on a specific time before meeting somewhere?"],
"21": ["What is the weather like outside?","Where is Person 2 going?","Why might someone check the weather before deciding what to wear?"],
"22": ["What drink does Person 2 like?","When does Person 2 usually drink it?","Why might people have a favorite drink for a specific time of day?"],
"23": ["What animal does Person 2 like?","What is the animal's name?","Why might people give their pets names that describe their personality?"],
"24": ["Where do they go on weekends?","Who does Person 2 go with?","Why might weekend routines with family become special traditions?"],
"25": ["What subject activity does Person 2 like?","Is the activity difficult for Person 2?","Why might some students find certain school activities easier than others?"],
"26": ["Which does Person 2 like more, the food or the drink?","How often does Person 2 have it?","Why might people enjoy sharing their favorite food with family?"],
"27": ["What day is it in this conversation?","What time does the class start?","Why is it useful to prepare before a class starts?"],
"28": ["What color is Person 2's object?","Where did Person 2 buy it?","Why might a cheaper price make someone happier about a purchase?"],
"29": ["What animal does Person 2 have?","Where does the animal sleep?","Why might a pet sleeping in someone's room create a closer bond?"],
"30": ["What season does Person 2 like?","What does Person 2 do in that season?","Why might people enjoy different activities depending on the season?"],
"31": ["Does Person 2 help at home?","What does Person 2 do to help?","Why might helping at home be a good habit to develop?"],
"32": ["What time is it in the conversation?","Are they late for class?","Why might checking the time before leaving help avoid being late?"],
"33": ["Which does Person 2 like more, the hobby or the sport?","Who does Person 2 do it with?","Why might doing an activity with friends make it more enjoyable?"],
"34": ["What season is Person 2's birthday in?","How old will Person 2 be?","Why do people often celebrate birthdays with a party?"],
"35": ["Does Person 2 like their family?","What do they do together?","Why might eating meals together be an important family tradition?"],
"36": ["What is the weather like in that season?","What does Person 2 wear then?","Why might people choose different clothes depending on the season?"],
"37": ["Does Person 2 have homework today?","When will Person 2 do it?","Why might doing homework right after school be a good habit?"],
"38": ["What does Person 2 usually drink at the place?","How often does Person 2 go there?","Why might a regular place become a favorite spot for friends to meet?"],
"39": ["Does Person 2 like their object?","Who gave it to Person 2?","Why might a gift from family feel more special than something bought alone?"],
"40": ["What time does Person 2 go to bed?","What did Person 2 do today?","Why is it important to get enough sleep before school?"],
"41": ["Does Person 2 like going to the place?","How often does Person 2 go?","Why might a regular routine with family create good memories?"],
"42": ["What is Person 2's favorite food?","Who cooks it for Person 2?","Why might food cooked by family taste more special?"],
"43": ["Does Person 2 like school?","What is Person 2's favorite part?","Why might having good teachers make school more enjoyable?"],
"44": ["What day is it in the conversation?","What time is the class?","Why might someone feel excited before a class they enjoy?"],
"45": ["Does Person 2 like animals?","What would Person 2 name a new pet?","Why do people often choose meaningful names for their pets?"],
"46": ["What does Person 2 like to do at the place?","Who does Person 2 usually go with?","Why might a favorite place feel more special when shared with family?"],
"47": ["Does Person 2 like this kind of weather?","What does Person 2 do on days like this?","Why might people enjoy staying inside during certain weather?"],
"48": ["Does Person 2 like their teacher?","Why does Person 2 like them?","Why might a teacher who explains well make a class more enjoyable?"],
"49": ["What does Person 2 do after school?","What time does Person 2 finish homework?","Why might doing homework early leave more free time later?"],
"50": ["Does Person 2 like their neighborhood?","Is it near the place mentioned?","Why might living in a quiet area be appealing to some people?"]
};

if (typeof module !== 'undefined' && module.exports) module.exports = QUESTIONS_LONG_A1;
