const QUESTIONS_LONG_B1 = {
"1": ["What subject is Person 2 considering studying?","What is Person 2 worried about?","Why might talking to a career counselor help someone make a clearer decision about their future?"],
"2": ["What does Person 2 do to limit screen time?","When does Person 2 try to avoid using their phone?","Why might limiting screen time before bed improve someone's sleep?"],
"3": ["What does Person 1 think is the biggest challenge facing the place?","Would Person 2 give up their own transportation?","Why might convenience be a bigger factor than environmental concern for many people choosing transport?"],
"4": ["What change would Person 1 make to the school?","What kind of variety does Person 1 want in the curriculum?","Why might practical projects help students engage more than pure theory?"],
"5": ["Would Person 2 prefer a big city or a small town?","Why does Person 2 prefer that lifestyle?","Why might someone value peace and quiet over more opportunities in a city?"],
"6": ["Which language would Person 2 choose to learn?","What is motivating Person 2 to learn it?","Why might having a travel goal make learning a new language feel more meaningful?"],
"7": ["How does Person 2 deal with stress before exams?","Does Person 2 take breaks while studying?","Why might taking regular breaks help prevent burnout while studying?"],
"8": ["Does Person 2 prefer that movie genre over others?","Was the movie worth recommending to others?","Why might recommending a movie to friends show how much someone enjoyed it?"],
"9": ["Would Person 2 take a hobby-related class if offered?","What benefit does Person 2 mention?","Why might creative classes help reduce stress for students?"],
"10": ["Does Person 2 prefer studying alone or in groups?","Has Person 2 tried group study sessions before?","Why might some people focus better while studying alone?"],
"11": ["What skill did Person 2 mention learning outside of school?","How did Person 2 improve at it?","Why might using a planner help someone feel less overwhelmed?"],
"12": ["What does Person 2 think about part-time jobs for students?","What benefit does Person 2 mention?","Why might balancing hours carefully help a part-time job not affect studies?"],
"13": ["What does Person 1 think about the amount of homework?","What would Person 1 prefer instead?","Why might class-based practice sometimes be more useful than homework alone?"],
"14": ["Does Person 2 prefer traveling alone or with others?","What advantage does Person 2 mention?","Why might traveling alone help build someone's confidence?"],
"15": ["Does Person 2 think study apps are more effective than textbooks?","What downside does Person 2 mention?","Why might notifications from a study app sometimes be distracting?"],
"16": ["What qualities does Person 2 think competitive sports teach?","Does the pressure to win cause stress?","Why might a coach's approach affect how much pressure players feel?"],
"17": ["Does Person 1 think comparing yourself to classmates is healthy?","What does Person 2 do instead?","Why might focusing on personal progress reduce unnecessary stress?"],
"18": ["What does Person 2 think school uniforms help reduce?","What concern does Person 1 raise?","Why might uniforms reduce social pressure around fashion at school?"],
"19": ["What hobby did Person 2 recently start?","Was it difficult to get started?","Why might trying new hobbies regularly keep life more interesting?"],
"20": ["What kind of businesses have classmates started?","Does it take away from their studies, in Person 2's opinion?","Why might managing time well be important for a student running a small business?"],
"21": ["Does Person 2 prefer planning carefully or staying flexible?","What risk does Person 1 mention about planning too rigidly?","Why might staying flexible help someone take advantage of unexpected opportunities?"],
"22": ["Why does Person 2 think some students get more attention from teachers?","Has Person 2 experienced this themselves?","Why might larger classes make it harder for teachers to give equal attention?"],
"23": ["What benefits has Person 2 gained from joining a club?","Does it add pressure to their schedule?","Why might the benefits of joining a club outweigh the extra time it takes?"],
"24": ["What benefit has Person 2 noticed from journaling?","Is it hard to stay consistent?","Why might the first few weeks of a new habit be the hardest?"],
"25": ["What kind of decisions does Person 1 think students should have more say in?","Would teachers actually listen, in Person 2's opinion?","Why might students having a say in decisions make school feel more collaborative?"],
"26": ["How long of a social media break does Person 2 recommend?","What did Person 2 notice during their own break?","Why might taking a break from social media help someone feel calmer?"],
"27": ["What topics does Person 2 think financial literacy should include?","Why hasn't it been taught more already, in Person 2's opinion?","Why might budgeting and saving be important skills to learn early?"],
"28": ["What qualities does Person 1 think make a good mentor?","Has Person 2 had a mentor?","Why might having a mentor shape someone's whole perspective on life?"],
"29": ["What does Person 1 think schools focus too much on?","What alternative does Person 1 suggest?","Why might project-based assessments better show a student's real skills?"],
"30": ["What does Person 2 do to relax during holidays?","Does it feel strange to be offline at first?","Why might disconnecting during holidays be important for mental health?"],
"31": ["What dishes has Person 2 learned to cook?","Who helped Person 2 learn?","Why might learning to cook early build independence?"],
"32": ["What impact has volunteering had on Person 2?","Does it take time away from studying?","Why might volunteering teach empathy and responsibility?"],
"33": ["Does Person 2 prefer specializing early or exploring many subjects?","What benefit does Person 2 mention about exploring broadly?","Why might exploring different subjects help someone discover their real passion?"],
"34": ["What example of failure does Person 2 share?","How did Person 2 overcome it?","Why might learning from failure be more valuable than avoiding it altogether?"],
"35": ["What benefit does Person 2 mention about learning to code?","Is it difficult for people who dislike technology?","Why might coding improve someone's logical thinking, even outside programming?"],
"36": ["What hobby has helped Person 2 the most?","Does it take time away from studying?","Why might having a hobby actually make someone more productive overall?"],
"37": ["What does Person 2 think causes most student pressure today?","Does social media make it worse?","Why might constant comparison online increase pressure on students?"],
"38": ["What does Person 2 hope to gain from traveling before university?","Would it delay academic progress?","Why might travel experience be considered worth a delay in studies?"],
"39": ["What does Person 2's ideal daily routine look like?","Does it ever get boring?","Why might a structured routine improve someone's productivity?"],
"40": ["What electives would Person 2 choose if given the choice?","Would it make school scheduling harder?","Why might more elective choices make learning feel more meaningful to students?"],
"41": ["Why do some students hesitate to ask for help, according to Person 2?","Has Person 2 struggled with this themselves?","Why might asking for help actually be a sign of strength rather than weakness?"],
"42": ["What benefit has Person 2 noticed from practicing public speaking?","Was it intimidating at first?","Why might public speaking skills help in many areas of life, not just presentations?"],
"43": ["What would Person 2 do during a gap year?","Would they lose academic momentum?","Why might a gap year help someone gain clarity about their future?"],
"44": ["What makes a friendship meaningful to Person 2?","Does it get harder to maintain friendships after school?","Why might effort be necessary to keep friendships alive over time?"],
"45": ["What situation has taught Person 2 the most patience?","Is it frustrating to practice patience under pressure?","Why might patience affect almost every part of a person's life?"],
"46": ["What kind of business ideas have worked well, according to Person 2?","Does it distract from academic responsibilities?","Why might starting a small business teach practical, real-world skills?"],
"47": ["How often does Person 2 reflect on their goals?","Does reflecting ever feel repetitive?","Why might regular reflection help someone stay aligned with what matters to them?"],
"48": ["What has helped Person 2 learn about other cultures?","Was it difficult without much travel experience?","Why might books and films be useful for learning about different cultures?"],
"49": ["How does Person 2 measure their own progress?","Does it get difficult to stay motivated this way?","Why might comparing yourself to your past self reduce unnecessary pressure?"],
"50": ["What boundary has worked best for Person 2?","Is it hard to stick to during busy weeks?","Why might setting boundaries between schoolwork and rest help prevent burnout?"]
};

if (typeof module !== 'undefined' && module.exports) module.exports = QUESTIONS_LONG_B1;
